### PR TITLE
[Adapter]: Deduplicate cluster creation for BackendRefs

### LINKED ISSUE #828: Deduplicate router cluster creation based on backendRefs
**Description:**
With the current implementation a cluster is created per each of the resources in a HttpRoute. This consumes excessive resources in the router and it is not required to maintain a cluster per resource. So this should be fixed to create clusters per unique backendRefs. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by NomadXD**
## Purpose
Deduplicate cluster creation for backendRefs for HttpRoutes with same BackendRef to prevent excessive resource consumption in envoy proxy.

## Approach
Use `reflect.DeepEqual` to compare Endpoints before cluster creation and reuse the already existing cluster if the endpoints are the same.

## Automation tests
 - Unit tests 
   >  Two units test cases are added: `TestCreateRoutesWithClustersSameBackendRefs, TestCreateRoutesWithClustersDifferentBackendRefs`
 - Integration tests
   > N/A

## Fixes  #828

### CODE REVIEW

File: adapter/internal/oasparser/envoyconf/routes_with_clusters.go [hunk 1]
```diff
@@ -94,26 +95,36 @@ func CreateRoutesWithClusters(mgwSwagger model.MgwSwagger, interceptorCerts map[
...
-		if err != nil {
-			logger.LoggerOasparser.Errorf("Error while adding resource level endpoints for %s:%v-%v. %v",
-				apiTitle, apiVersion, resourcePath, err.Error())
+		existingClusterName := getExistingClusterName(*endpoint, processedEndpoints)
+		
+		if existingClusterName == "" {
+			clusterName = getClusterName(endpoint.EndpointPrefix, organizationID, vHost, mgwSwagger.GetTitle(), apiVersion, resource.GetID())
+			cluster, address, err := processEndpoints(clusterName, endpoint, timeout, basePath)
+			if err != nil {
+				logger.LoggerOasparser.Errorf("Error while adding resource level endpoints for %s:%v-%v. %v",
```
Comment (AmaliMatharaarachchi) [inline adapter/internal/oasparser/envoyconf/routes_with_clusters.go:113]: please follow the new error log format. example:
```
logger.LoggerXds.ErrorC(logging.GetErrorByCode(2231, mgwSwagger.GetTitle(), mgwSwagger.GetVersion(), resource.GetPath(), err.Error()))
```

**Review by AmaliMatharaarachchi — APPROVED** [review]

File: adapter/internal/oasparser/envoyconf/routes_with_clusters.go (hunk 1 above)
Comment (NomadXD) [reply adapter/internal/oasparser/envoyconf/routes_with_clusters.go]: fixed
